[package]
name = "rusql-executor"
description = "Query executor for rusql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rusql-core.workspace = true
rusql-planner.workspace = true
rusql-sql.workspace = true
rusql-storage.workspace = true
sqlparser.workspace = true
thiserror.workspace = true
