[package]
name = "rusql-protocol"
description = "MySQL wire protocol for rusql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rusql-i18n.workspace = true
sha1.workspace = true
sha2.workspace = true
rsa.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "net"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
